version: "3"

services:
  parser:
    container_name: parser
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    # volumes:
    #   - ./node_modules:/home/node/app/node_modules
    #   - ./:/home/node/app


